modules:
  prefix_inspections:
      bin:
      - PATH
      lib:
      - LD_LIBRARY_PATH 
      lib64:
      - LD_LIBRARY_PATH 
      man:
      - MANPATH
      share/man:
      - MANPATH
      share/aclocal:
      - ACLOCAL_PATH
      lib/pkgconfig:
      - PKG_CONFIG_PATH
      lib64/pkgconfig:
      - PKG_CONFIG_PATH
      share/pkgconfig:
        - PKG_CONFIG_PATH
      ./:
        - CMAKE_PREFIX_PATH
  default:
    roots:
      tcl: $spack/share/spack/tcl
      lmod: $spack/share/spack/lmod
    arch_folder: false
    enable:
      - tcl
    tcl:
      projections:
        all: '{name}/{version}-{compiler.name}'
        +mpi: '{name}/{version}-{^mpi.name}-{compiler.name}'
        +mpi+cuda: '{name}/{version}-{^mpi.name}-{+cuda}'
      hash_length: 0
      all:
        autoload: 'direct'
        conflict:
          - '{name}'
        environment:
          set:
            '{name}_ROOT_DIR': '{prefix}'
      mpich:
        environment:
          set:
            'UCX_NET_DEVICES': 'mlx5_0:1'
            'MPIR_CVAR_ENABLE_GPU' : '0'
      openmpi:
        environment:
          set:
            'OMPI_MCA_osc' : 'ucx'
            'OMPI_MCA_pml' : '^ucx'
            'OMPI_MCA_btl_openib_if_include' : 'mlx5_0:1'
      include: ['nalu-wind','amr-wind','exawind']     
      exclude: ['%intel', '%gcc']        
