packages:
  mesa:
    variants: ~llvm +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  slurm:
    buildable: false
    externals:
    - spec: slurm@23-02-3
      prefix: /nopt/slurm/23.02.3
  cuda:
    buildable: false
    externals:
    - spec: cuda@11.7.0
      prefix: /nopt/nrel/apps/compilers/07-23/spack/opt/spack/linux-rhel8-icelake/gcc-8.4.0/cuda-11.7.0-co2zgjqa2pqc2gxmuklofeazclyrvosc
  hwloc:
    variants: +cuda
  hypre:
    version: [develop]
    variants: ~superlu-dist
  cudnn:
    version: [7.6.5.32-10.1-linux-x64]
  openmpi:
    buildable: False      
    externals:      
    - spec: openmpi@4.1.5%gcc
      prefix: /nopt/nrel/apps/mpi/07-23/spack/opt/spack/linux-rhel8-icelake/gcc-10.1.0/openmpi-4.1.5-s5tpzjd3y4scuw76cngwz44nuup6knjt
      modules:
        - openmpi/4.1.5-gcc
  mpich:
    buildable: False
    externals:
    - spec: mpich@4.1%gcc
      prefix: /nopt/nrel/apps/mpi/07-23/spack/opt/spack/linux-rhel8-icelake/gcc-10.1.0/mpich-4.1-xk5vtss62w2ujmy26axkbvpquekwww7z
      modules:
        - mpich/4.1-gcc
  intel-oneapi-mpi:
    buildable: False
    externals:
    - spec: intel-oneapi-mpi@2021.8.0%intel
      prefix: /nopt/nrel/apps/mpi/07-23/spack/opt/spack/linux-rhel8-icelake/intel-2021.6.0/intel-oneapi-mpi-2021.8.0-6pnag4mmmx6lvoczign5a4fslwvbgebb
      modules:
        - intel-oneapi-mpi/2021.8.0-intel
  cray-mpich:
    require: "@8.1.23"
    buildable: False
    externals:
    - spec: cray-mpich@8.1.23
      prefix: /opt/cray/pe/mpich/8.1.23/ofi/intel/19.0
      modules:
        - PrgEnv-intel      
        - cray-mpich/8.1.23
        - craype-network-ofi
        - libfabric/1.15.2.0
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  xpmem:
    variants: ~kernel-module 
    version: [2.6.3]
  all:
    variants: build_type=Release +mpi
    providers:
      mpi: [openmpi,intel-oneapi-mpi,mpich,mpt]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
# add cuda
# add ucx 
