packages:
  mesa:
    variants: ~llvm +opengl +glx swr=skx
  llvm:
    variants: +omp_debug+omp_tsan+cuda cuda_arch=70 build_type=Release
  slurm:
    buildable: false
    externals:
    - spec: slurm@22-05-7
      prefix: /nopt/slurm/22.05.7
  hwloc:
    variants: +cuda
  hypre:
    version: [develop]
    variants: ~superlu-dist
  cudnn:
    version: [7.6.5.32-10.1-linux-x64]
  openmpi:
    buildable: False      
    externals:      
    - spec: openmpi@4.1.5
      prefix: /sfs/nopt/nrel/apps/mpi/03-23/spack/opt/spack/linux-rhel8-icelake/gcc-10.1.0/openmpi-4.1.5-uznqw2wnj6l4k3xdnpoklyllq3iz3s3v
  intel-oneapi-mpi:
    buildable: False      
    externals:      
    - spec: intel-oneapi-mpi@2021.8.0
      prefix: /sfs/nopt/nrel/apps/mpi/01-23/spack/opt/spack/linux-rhel8-icelake/intel-2021.6.0/intel-oneapi-mpi-2021.8.0-6pnag4mmmx6lvoczign5a4fslwvbgebb
  mpich:
    variants: +cuda+slurm+hydra cuda_arch=70 netmod=ucx device=ch4 pmi=pmi2
  py-horovod:
    variants: tensor_ops=mpi frameworks=pytorch,tensorflow
  py-tensorflow:
    variants: +cuda cuda_arch=70 +mpi +nccl
  py-torch:
    variants: +cuda cuda_arch=70 +cudnn +nccl
  fftw:
    variants: +mpi+fma simd=avx512
  libfabric:
    variants: fabrics=verbs
  pgi:
    variants: +nvidia
  xpmem:
    variants: ~kernel-module 
    version: [2.6.3]
  all:
    variants: build_type=Release +mpi
    providers:
      mpi: [openmpi,intel-oneapi-mpi,mpich,mpt]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      gl: [osmesa+opengl]
      glx: [osmesa+glx]
# add cuda
# add ucx 
